spring:
  jpa:
    hibernate:
      ddl-auto: create

#spring:
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            scripts:
#              action: create
#              create-target: generated_schema.sql